compile:
  stage: build
  image: arkark/latexmk:full
  script:
    - echo "Compiling LaTeX with TexLive."
    - mkdir pdf
    - mkdir pdf/chapters
    - mkdir pdf/templates
    - latexmk -pdf thesis.tex -output-directory=./pdf
  tags:
    - latex
