compile_thesis:
  stage: build
  image: arkark/latexmk:full
  script:
    - rm /root/.latexmkrc
    - latexmk -pdf thesis.tex
  tags:
    - latex
  artifacts:
    paths:
      - ./*.pdf

compile_expose:
  stage: build
  image: arkark/latexmk:full
  script:
    - rm /root/.latexmkrc
    - latexmk -pdf expose.tex
  tags:
    - latex
  artifacts:
    paths:
      - ./*.pdf